# Generated by Django 6.0.2 on 2026-03-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_destination_image'),
        ('users', '0005_securityquestion_usersecurityanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='constraint_tags',
            field=models.ManyToManyField(blank=True, related_name='trips', to='users.constrainttag'),
        ),
    ]
