# Generated by Django 6.0.2 on 2026-04-11 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_constraint_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
        migrations.CreateModel(
            name='TripExpenseBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_budgets', to='trips.trip')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
