# Generated by Django 6.0.2 on 2026-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_cover_image_tripexpensebudget'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
