# Generated by Django 6.0.2 on 2026-04-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_tripreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
