# Generated by Django 6.0.2 on 2026-04-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_trip_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
