# Generated by Django 6.0.2 on 2026-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0013_tripinvitation_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tripinvitation',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='tripinvitation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when notification was marked as read', null=True),
        ),
    ]
