# Generated by Django 6.0.2 on 2026-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_address_userprofile_citizenship_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('activity', 'Activity'), ('destination', 'Destination'), ('experience', 'Experience')], default='activity', max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_match_age',
            field=models.IntegerField(default=100, help_text='Maximum age for travel companions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_match_age',
            field=models.IntegerField(default=18, help_text='Minimum age for travel companions'),
        ),
        migrations.CreateModel(
            name='ConstraintTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('diet', 'Diet'), ('lifestyle', 'Lifestyle'), ('values', 'Values'), ('age_range', 'Age Range')], max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='constraint_tags',
            field=models.ManyToManyField(blank=True, help_text='Diet, lifestyle, values - these must match for compatibility', related_name='users', to='users.constrainttag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.interest'),
        ),
    ]
