# Generated by Django 6.0.2 on 2026-03-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='status',
        ),
    ]
