# Generated by Django 6.0.2 on 2026-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_userprofile_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive email notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='friend_requests',
            field=models.BooleanField(default=True, help_text='Get notified about friend requests'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_profile',
            field=models.BooleanField(default=True, help_text='Allow others to see your profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='searchable_by_email',
            field=models.BooleanField(default=True, help_text='Allow users to find you by email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='share_trip_activity',
            field=models.BooleanField(default=True, help_text='Share your trip activity with others'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_online_status',
            field=models.BooleanField(default=True, help_text="Show when you're online"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trip_updates',
            field=models.BooleanField(default=True, help_text='Get notified about trip updates'),
        ),
    ]
