# Generated by Django 6.0.2 on 2026-04-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, help_text="User's current online status"),
        ),
    ]
