# Generated by Django 6.0.2 on 2026-04-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_kycprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycprofile',
            name='id_expiry_date',
            field=models.DateField(blank=True, help_text='ID/Passport expiry date', null=True),
        ),
    ]
