# Generated by Django 6.0.3 on 2026-03-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='decription',
            new_name='description',
        ),
    ]
