# Generated by Django 6.0.2 on 2026-04-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when message was marked as read', null=True),
        ),
    ]
